apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myspring
  template:
    metadata:
      labels:
        app: myspring
    spec:
      containers:
        - name: myspring
          image: romeodms/springboot:v1.1           
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config-spring
                  key: APP_MESSAGE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-spring
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myspring
spec:
  ports:
    - nodePort: 32001
      port: 8080
      targetPort: 8080
  selector:
    app: myspring
  type: NodePort
